# .github/workflows/deploy.yml
name: Deploy Next.js site to GitHub Pages # ワークフロー名をより具体的に変更

on:
  push:
    branches: ["main"] # mainブランチへのプッシュでワークフローをトリガー
  workflow_dispatch: # GitHub ActionsのWeb UIから手動で実行できるようにする

permissions:
  contents: read   # リポジトリの内容を読み取る権限
  pages: write     # GitHub Pagesにデプロイする権限（★追加/確認★）
  id-token: write  # OpenID Connect (OIDC) を使用するための権限（Secrets利用に必要）（★追加/確認★）

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ビルドジョブ: 静的ファイルを生成し、成果物としてアップロード
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # ★v3からv4に更新。最新のアクションを使用★

      - name: Setup Node.js
        uses: actions/setup-node@v4 # ★v3からv4に更新。最新のアクションを使用★
        with:
          node-version: "20" # Node.jsのバージョンを指定（安定版のLTS 20を推奨）
          cache: "npm"       # npmキャッシュを有効にしてビルド時間を短縮

      - name: Install dependencies
        run: npm install

      - name: Build Next.js site
        env:
          # GitHubリポジトリのSecretsに登録したNotion APIの環境変数を渡す
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: npm run build # Next.jsのビルドコマンドを実行

      # .nojekyll ファイルをビルド成果物ディレクトリ（out）に追加
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll # ビルド後に out ディレクトリ内に作成

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3 # ★このアクションでビルド成果物（outディレクトリ）をアップロード★
        with:
          path: ./out # 静的エクスポートで生成されるディレクトリのパス

  # デプロイジョブ: アップロードされた成果物をGitHub Pagesにデプロイ
  deploy:
    environment:
      name: github-pages # GitHub Pages環境を指定
      url: ${{ steps.deployment.outputs.page_url }} # デプロイ後のURLを環境変数として利用可能にする
    runs-on: ubuntu-latest
    needs: build # buildジョブが成功した後に実行

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # ★GitHub公式のデプロイアクションを使用★